[gateways.grafbase]
# Image to use.
image = "ghcr.io/grafbase/gateway:0.48.0"
# Arguments to use when running the gateway
arguments = [
    "--schema",
    "/data/schema.graphql",
    "--config",
    "/data/grafbase.toml",
]
