[package]
name = "subgraph"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-graphql.workspace = true
axum.workspace = true
quick_cache.workspace = true
rapidhash.workspace = true
serde_json.workspace = true
tokio.workspace = true
