[grafbase-no-cache]
label = "Grafbase Gateway (no cache)"
image = "ghcr.io/grafbase/gateway:0.48.0"
args = [
    "--config",
    "/gateways/grafbase/no-cache.toml",
    "-s",
    "/supergraph/schema.graphql",
]

[grafbase]
label = "Grafbase Gateway (no cache)"
image = "ghcr.io/grafbase/gateway:0.48.0"
args = [
    "--config",
    "/gateways/grafbase/grafbase.toml",
    "-s",
    "/supergraph/schema.graphql",
]

[cosmo]
label = "Cosmo Router"
# 2025-08-28
image = "ghcr.io/wundergraph/cosmo/router:0.246.2"
args = ["/router", "-config", "/gateways/cosmo/config.yml"]

[cosmo-no-cache]
label = "Cosmo Router (no cache)"
# 2025-08-28
image = "ghcr.io/wundergraph/cosmo/router:0.246.2"
args = ["/router", "-config", "/gateways/cosmo/no-cache.yml"]

# Compiled from https://github.com/Finistere/router/tree/qp-disable-cache
# To allow disabling the query plan cache entirely which the Apollo router doesn't allow (must be at least 1).
# After checking out the repo, run:
# `docker build . -t apollo-router-no-cache`
# As of 2024-08-26 it is based on 58b86ee4b5c2b603e294e5440f5924996d908b5b which past 2.5.0, but before the 2.6.0 release.
[apollo-router-no-cache]
label = "Apollo Router (no cache)"
image = "apollo-router-no-cache"
args = [
    "-c",
    "/gateways/apollo-router/no-cache.yml",
    "-s",
    "/supergraph/schema.graphql",
]

[apollo-router]
label = "Apollo Router"
image = "ghcr.io/apollographql/router:v2.6.0"
args = [
    "-c",
    "/gateways/apollo-router/router.yml",
    "-s",
    "/supergraph/schema.graphql",
]

[hive]
label = "Hive Gateway"
image = "ghcr.io/graphql-hive/gateway:1.16.3"
args = ["supergraph", "/supergraph/schema.graphql", "-p", "4000"]
