[package]
name = "subgraph"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7"
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
rand = "0.8"
rand_chacha = "0.3"
serde_json = "1"
anyhow = "1"
once_cell = "1"