[package]
name = "fed"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-graphql.workspace = true
once_cell.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde_json.workspace = true
subgraph.workspace = true
tokio.workspace = true
